// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CleanArchitecture.CodeGenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCodeGeneratorPkgString = "da3d4428-7855-4b22-a0e6-a7b9a6c7aa5e";
        public static Guid guidCodeGeneratorPkg = new Guid(guidCodeGeneratorPkgString);

        public const string guidCodeGeneratorCmdSetString = "4c7a4f97-2988-45ec-af7c-8984fc72c5e1";
        public static Guid guidCodeGeneratorCmdSet = new Guid(guidCodeGeneratorCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdidMyCommand = 0x0100;
    }
}