// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CleanArchitecture.CodeGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "6A168388-B6A2-42F9-BA5A-B577D3CD4DB5";
        public const string Name = "CleanArchitecture CodeGenerator For Blazor App";
        public const string Description = @"The fastest and easiest way to generate application features code that up to clean architecture principles  for Blazor Server Application";
        public const string Language = "en-US";
        public const string Version = "0.8";
        public const string Author = "7d4891e8-2f14-45ce-a707-8a3915e9b380";
        public const string Tags = "templat,CleanArchitecture,CodeGenerator";
    }
}
