// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CleanArchitecture.CodeGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "CleanArchitecture_CodeGenerator_BlazorApp";
        public const string Name = "CleanArchitecture CodeGenerator For Blazor App";
        public const string Description = @"The fastest and easiest way to generate application features code that up to clean architecture principles  for Blazor Server Application";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "neozhu";
        public const string Tags = "templat,CleanArchitecture,CodeGenerator";
    }
}
